# Generated by Django 4.1.4 on 2023-02-22 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_is_published_post_pinned_post_alter_post_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='photo',
            field=models.ImageField(blank=True, upload_to='backgrounds/%Y/%m/%d/', verbose_name='Фон'),
        ),
        migrations.AddField(
            model_name='category',
            name='short_description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='category',
            name='tagline',
            field=models.CharField(blank=True, max_length=100, verbose_name='Слоган'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pinned_post',
            field=models.BooleanField(default=False, verbose_name='Закрепить пост'),
        ),
    ]
