# Generated by Django 4.1.4 on 2023-04-06 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
